DROP USER IF EXISTS root;
DROP TABLE IF EXISTS feeds CASCADE;
DROP TABLE IF EXISTS query_articles CASCADE;
DROP TABLE IF EXISTS query_words CASCADE;
DROP TABLE IF EXISTS articles CASCADE;
DROP TABLE IF EXISTS queries CASCADE;
DROP TABLE IF EXISTS sources CASCADE;
